#!/usr/bin/env sh

echo "🚀 Formatting Repository Files..."

echo "🎨 Running frontend formatting..."
cd frontend
yarn format

echo "🔙 Returning to project root..."
cd ..

echo "☕ Running Java checks..."
./scripts/check-java.sh

echo "✨ All formatting complete!"
