spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:atlas_journey}
    username: ${POSTGRES_USERNAME:atlas_journey}
    password: ${POSTGRES_PASSWORD:password}
